const styles = {
    copyMessage: {
        width: '100vw',
        height: '100vh',
        margin: 0,
        padding: 0,
        background: '#222',
        fontFamily: 'Josefin Sans, Helvetica, Helvetica Neue, Arial, sans-serif',
        fontSize: '16px',
        fontWeight: 'normal',
    },   
    stage: {
        width: '100%',
        height: '100%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    wrapper: {
        position: 'absolute',
        top: '40vh',
        left: '40vw',
        color: '#fff',
        fontSize: '4.5rem',
        textTransform: 'uppercase',
        letterSpacing: '0.25rem',
        paddingTop: '0.65rem',
        paddingLeft: '0.5rem',
        paddingRight: '0.36rem',
        paddingBottom: '0.2rem',
    },
    slash: {
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%) rotate(-24deg) scaleY(0)',
        transformOrigin: 'center center',
        width: '0.25rem',
        height: '145%',
        background: '#fff',
        zIndex: 4,
        animation: 'slash 6s ease-in ',
        "&:before": {
            content: '',
            display: 'block',
            position: 'absolute',
            top: '50%',
            left: '50%',
            transform: 'translate(-50%, -50%)',
            width: '0.75rem',
            height: '120%',
            background: '#232323',
            zIndex: -1,
        },
        "&:after": {
            content: '',
            display: 'block',
            position: 'absolute',
            top: 0,
            left: 0,
            width: '100%',
            height: '100%',
            background: '#fff',
        }
    },
    sides: {
        position: 'absolute',
        width: '100%',
        height: '100%',
        top: 0,
        left: 0,
        overflow: 'hidden',
        "& .side":{
            position: 'absolute',
            background: '#fff',
        }
    },
}

export default styles;